/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();

    }

    @Test public void rollTest(){

       assertEquals(3,Library.roll(3).size());


    }
    @Test public void containsDuplicatesTest (){
        int [] arr1 = {1,2,3,4,4};
        int [] arr2 = {1,2,3,4,5};
        assertEquals(true,Library.containsDuplicates(arr1));
        assertEquals(false,Library.containsDuplicates(arr2));
    }
    @Test public void averagesTest (){

        int[][] arr = {
                {1, 1, 1, 1, 1, 1, 1},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        assertEquals(1,Library.averages(arr));

    }
}
