/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package basiclibrary;
import java.util.Scanner;
import java.util.ArrayList;

public class Library {
    public static void main(String[] args) {
//----------------------roll---------------------
        Scanner input = new Scanner(System.in);
        System.out.println("Please Enter Number Of Roll Dice");
       int numberOfRollDice = input.nextInt();
      System.out.println(roll(numberOfRollDice));
//---------------------containsDuplicates----------
      int [] array = {5,2,3,4,5};
      System.out.println(containsDuplicates(array));

//----------------------Averages-------------------
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

       System.out.println(averages(weeklyMonthTemperatures));

    }

    static ArrayList<Integer> roll (int n) {
        ArrayList<Integer> numbers = new ArrayList<Integer>();
        for (int i = 0; i < n; i++) {
            numbers.add((int) (Math.random() * (6+1 - 1)) + 1);

        }
        return numbers;
    }


    static boolean containsDuplicates(int [] arr){
        for (int i=0; i< arr.length-1;i++ ){

            for (int j=i+1;j<arr.length;j++){

               if(arr[i] == arr[j]){
                   return true;
               }
            }
        }
        return false;
    }

    static int averages(int [][] arrays){
        int average;
        ArrayList<Integer> arrayOfAverages = new ArrayList<Integer>();

        for (int[] array : arrays){
            int total = 0;
            for (int num : array){
                total+=num;
            }

            arrayOfAverages.add(total/array.length);

        }
        average = arrayOfAverages.get(0);
        for (int i = 1; i < arrays.length;i++){
           if (average > arrayOfAverages.get(i)){
               average = arrayOfAverages.get(i);
           }

        }

        return average;

    }


}
